meta:
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-lucid
    version: '2624'

director_uuid: EDIT_ME # EDIT ME

name: oracle-xe

releases:
- name: oracle-xe
  version: latest

compilation:
  cloud_properties:
    ram: 3072
    disk: 8192
    cpu: 2
  network: oracle-xe-network
  reuse_compilation_vms: true
  workers: 1

update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  update_watch_time: 1000-60000

jobs:
- instances: 1
  name: oracle-xe
  networks:
  - name: oracle-xe-network
    static_ips:
#    - 10.85.29.10
    - 10.85.29.30 # EDIT ME
#    - 10.85.29.10
#    - 10.85.29.14
  resource_pool: oracle-xe-resource-pool
  persistent_disk: 8192
  templates:
  - name: oracle_xe_node
    version: latest

networks:
- name: oracle-xe-network
  subnets:
  - range: 10.85.29.0/24 # EDIT ME
    gateway: 10.85.29.1 # EDIT ME
    cloud_properties:
      name: goose # EDIT ME
    dns:
    - 10.85.29.91 # EDIT ME
    - 10.80.130.1 # EDIT ME
    reserved:
    - 10.85.29.2-10.85.29.25 # EDIT ME
    - 10.85.29.31-10.85.29.254 # EDIT ME
    static:
    - 10.85.29.30 # EDIT ME

resource_pools:
- cloud_properties:
    ram: 3072
    disk: 8192
    cpu: 2
  name: oracle-xe-resource-pool
  network: oracle-xe-network
  size: 3
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-lucid
    version: '2624'

properties:
  networks:
    apps: "oracle-xe-network"
  oracle_xe:
    xe_install_download_url: "http://12.1.1.1:7777/fileserver/oracle-xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip" # EDIT ME
    listener:
      port: 1521
    memory:
      pga_target: 150
      sga_target: 550
    sysuser: welcome1
    ootb:
     tablespace:
       name: example
       size: 100
     user:
       name: servicebroker
       passwd: s3cr3t
  oracle_xe_sb:
    jdbc_driver_download_url: "http://12.1.1.1:7777/fileserver/oracle-xe/ojdbc7.jar" # EDIT ME
    listen_port: 9000
    run_arg: "org.springframework.boot.loader.JarLauncher" # EDIT ME
    service:
      service_port: 1521
      service_sid: XE
    memory:
      min_heap: 512
      max_heap: 512
    credentials:
      system:
        username: system
        passwd: welcome1
      sbuser:
        username: servicebroker
        passwd: s3cr3t
      on_demand_service_plans:
      - service_plan_name: Standard
        init_space_size: 64
        max_space_size: 512
        max_concurrent_conn: 5
      - service_plan_name: Platinum
        init_space_size: 64
        max_space_size: 512
        max_concurrent_conn: 15

