meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

director_uuid: DIRECTOR_UUID # EDIT ME

name: oracle-xe-complete

releases:
- name: oracle-xe
  version: latest

compilation:
  cloud_properties:
    name: random
  network: oracle-xe-network
  reuse_compilation_vms: true
  workers: 1

update:
  canaries: 1
  canary_watch_time: 1000-900000
  max_in_flight: 3
  update_watch_time: 1000-900000

jobs:
- instances: 1
  name: oracle-xe
  release: oracle-xe
  networks:
  - name: oracle-xe-network
    static_ips:
#    - 10.244.3.10
    - 10.244.3.6     # EDIT ME
#    - 10.244.3.10
#    - 10.244.3.14
  resource_pool: oracle-xe-resource-pool
  templates:
  - name: oracle_xe_node
  - name: oracle_xe_sb
#- instances: 1
#  name: oracle-xe-sb
#  networks:
#  - name: oracle-xe-network
#    static_ips:
#    - 10.244.3.10
#  resource_pool: oracle-xe-resource-pool
#  templates:
#  - name: oracle_xe_sb
#    release: oracle-xe

networks:
- name: oracle-xe-network
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.3.0/30
    reserved:
    - 10.244.3.1
    static:
    - 10.244.3.2
  - cloud_properties:
      name: random
    range: 10.244.3.4/30
    reserved:
    - 10.244.3.5
    static:
    - 10.244.3.6
  - cloud_properties:
      name: random
    range: 10.244.3.8/30
    reserved:
    - 10.244.3.9
    static:
    - 10.244.3.10
  - cloud_properties:
      name: random
    range: 10.244.3.12/30
    reserved:
    - 10.244.3.13
    static:
    - 10.244.3.14
  - cloud_properties:
      name: random
    range: 10.244.3.16/30
    reserved:
    - 10.244.3.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.20/30
    reserved:
    - 10.244.3.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.24/30
    reserved:
    - 10.244.3.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.28/30
    reserved:
    - 10.244.3.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.32/30
    reserved:
    - 10.244.3.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.36/30
    reserved:
    - 10.244.3.37
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.40/30
    reserved:
    - 10.244.3.41
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.44/30
    reserved:
    - 10.244.3.45
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.48/30
    reserved:
    - 10.244.3.49
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.52/30
    reserved:
    - 10.244.3.53
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.56/30
    reserved:
    - 10.244.3.57
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.60/30
    reserved:
    - 10.244.3.61
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.64/30
    reserved:
    - 10.244.3.65
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.68/30
    reserved:
    - 10.244.3.69
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.72/30
    reserved:
    - 10.244.3.73
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.76/30
    reserved:
    - 10.244.3.77
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.80/30
    reserved:
    - 10.244.3.81
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.84/30
    reserved:
    - 10.244.3.85
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.88/30
    reserved:
    - 10.244.3.89
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.92/30
    reserved:
    - 10.244.3.93
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.96/30
    reserved:
    - 10.244.3.97
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.100/30
    reserved:
    - 10.244.3.101
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.104/30
    reserved:
    - 10.244.3.105
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.108/30
    reserved:
    - 10.244.3.109
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.112/30
    reserved:
    - 10.244.3.113
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.116/30
    reserved:
    - 10.244.3.117
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.120/30
    reserved:
    - 10.244.3.121
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.124/30
    reserved:
    - 10.244.3.125
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.128/30
    reserved:
    - 10.244.3.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.132/30
    reserved:
    - 10.244.3.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.136/30
    reserved:
    - 10.244.3.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.140/30
    reserved:
    - 10.244.3.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.144/30
    reserved:
    - 10.244.3.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.148/30
    reserved:
    - 10.244.3.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.152/30
    reserved:
    - 10.244.3.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.156/30
    reserved:
    - 10.244.3.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.160/30
    reserved:
    - 10.244.3.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.164/30
    reserved:
    - 10.244.3.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.168/30
    reserved:
    - 10.244.3.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.172/30
    reserved:
    - 10.244.3.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.176/30
    reserved:
    - 10.244.3.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.180/30
    reserved:
    - 10.244.3.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.3.184/30
    reserved:
    - 10.244.3.185
    static: []

resource_pools:
- cloud_properties:
    name: random
  name: oracle-xe-resource-pool
  network: oracle-xe-network
  size: 3
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

properties:
  oracle_xe:
    xe_install_download_url: "http://12.1.1.1:7777/fileserver/oracle-xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip" # EDIT ME
    listener:
      port: 1521
    memory:
      pga_target: 150
      sga_target: 550
    sysuser: welcome1
    ootb:
     tablespace:
       name: servicebroker
       size: 256
     user:
       name: servicebroker
       passwd: s3cr3t
  oracle_xe_sb:
    jdbc_driver_download_url: "http://12.1.1.1:7777/fileserver/oracle-xe/ojdbc7.jar" # EDIT ME
    listen_port: 9000
    service:
      service_port: 1521
      service_sid: XE
    memory:
      min_heap: 512
      max_heap: 512
    credentials:
      system:
        username: system
        passwd: welcome1
      sbuser:
        username: servicebroker
        passwd: s3cr3t
      on_demand_service_plans:
      - service_plan_name: Standard
        init_space_size: 64
        max_space_size: 512
        max_concurrent_conn: 5
      - service_plan_name: Platinum
        init_space_size: 64
        max_space_size: 512
        max_concurrent_conn: 15
