---
blobstore:
  provider: s3
  options:
    bucket_name: bosh-oracle-xe-release
    access_key_id: AKIAIUDAZ5JNJIAM7LRA
    secret_access_key: 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
final_name: oracle-xe
